### ISSUE TITLE
https://github.com/inversepath/usbarmory/wiki/Host-communication

### ISSUE THREAD

**Issue by Emzy** [inversepath/usbarmory#18]
This WIKI page has an error:
https://github.com/inversepath/usbarmory/wiki/Host-communication

At "Setup & Connection Sharing: Mac OS X (Yosemite) " the closing quotation marks are on the wrong place.

Right:
# Option 1: add NAT rule after en5 is up (USB armory already plugged and started)
$ echo "nat on en0 from en5:network to any -> (en0)" | sudo pfctl -f -

# Option 2: add NAT rule before USB armory is plugged, requires specifying its network
$ echo "nat on en0 from 10.0.0.0/8 to any -> (en0)" | sudo pfctl -f -

**Comment by abarisani** [comment]
Thanks for catching this, I just fixed it.
