### ISSUE TITLE
Wiki: uboot-mkimage is now part of u-boot-tools

### ISSUE THREAD

**Issue by northox** [inversepath/usbarmory#20]
Within the "[Preparing a bootable microSD image](https://github.com/inversepath/usbarmory/wiki/Preparing-a-bootable-microSD-image)" page  Prerequisites section, ``uboot-mkimage`` is now part of ``u-boot-tools``.

```
sudo apt-get install parted debootstrap binfmt-support qemu-user-static uboot-mkimage wget git xz-utils tar
```
should be
```
sudo apt-get install parted debootstrap binfmt-support qemu-user-static u-boot-tools wget git xz-utils tar
```

**Comment by andrejro** [comment]
Fixed. Thanks!
