### ISSUE TITLE
Unable to build modules after following "Preparing bootable sdcard" wiki page.

### ISSUE THREAD

**Issue by mex20** [inversepath/usbarmory#21]
The instructions that are provided on the 'Preparing a bootable Microsd card' page, do not allow you to build a kernel module. The /lib/modules/4.0.2/build and the /lib/modules/4.0.2/source are linked to the computer that prepared the microSD card's location of the linux-4.0.2 folder. example: "build -> /home/userfrombuildcomputer/linux-4.0.2"

**Comment by andrejro** [comment]
The instructions assumes that the successive kernel modules are also cross-compiled on
the host machine.
Alternatively, you can compile the linux kernel directly on the USB armory (it takes a while)
and the "make modules_install" will create the symbolic links (build and source) to the correct
path so the external modules will have all the needed kernel dependencies in place.
