### ISSUE TITLE
missing "auto usb0" in network configuration

### ISSUE THREAD

**Issue by jdesfossez** [inversepath/usbarmory#24]
Hi,

In the "Finalize and set the password" section of the "Preparing a bootable microSD image" page, there seems to be a "auto usb0" missing. At least when installing Trusty on the usbarmory the network does not work without that, and it should not break other ubuntu releases.

So, I would suggest replacing:
echo -e 'allow-hotplug usb0\niface usb0 inet static\n  address 10.0.0.1\n  netmask 255.255.255.0\n  gateway 10.0.0.2'| sudo tee -a ${TARGET_MNT}/etc/network/interfaces

By:
echo -e 'allow-hotplug usb0\nauto usb0\niface usb0 inet static\n  address 10.0.0.1\n  netmask 255.255.255.0\n  gateway 10.0.0.2'| sudo tee -a ${TARGET_MNT}/etc/network/interfaces

Thanks,

Julien

**Comment by andrejro** [comment]
Option added, thank you!
