### ISSUE TITLE
Preparing a bootable microSD image - Debian missing essential packages

### ISSUE THREAD

**Issue by Thireus** [inversepath/usbarmory#27]
The following packages are missing for the "Recent Debian and Ubuntu (x86 or x86-64)" section on the Wiki page https://github.com/inversepath/usbarmory/wiki/Preparing-a-bootable-microSD-image:

    sudo apt-get install [...] build-essential bc

These packages are required to build the kernel modules for example (tested against "make modules").

**Comment by abarisani** [comment]
Done, thanks for noting this.
