### ISSUE TITLE
Preparing a bootable microSD image - chroot commands dont work

### ISSUE THREAD

**Issue by jgriffiths** [inversepath/usbarmory#31]
Hi,

Building an image on Sid here.

The chroot commands listed don't work due to the ABI difference between host and chroot. Perhaps something is missing from the instructions: the command `sudo rm ${TARGET_MNT}/usr/bin/qemu-arm-static` does nothing as that file doesn't exist. Were the chroot commands meant to run under emulation? Regardless, the commands aren't needed as they can be done from the host:

`sudo chroot $TARGET_MNT systemctl mask getty-static.service` etc can be replaced with `ln -sf` of the service files to `/dev/null`, although all services were already masked in my case.

`sudo chroot $TARGET_MNT /usr/sbin/useradd -s /bin/bash -p $(sudo chroot $TARGET_MNT mkpasswd -m sha-512 usbarmory) -m usbarmory` can be replaced with the hosts useradd command by passing `-R $TARGET_MNT` to alter files in the chroot.

**Comment by andrejro** [comment]
Hi,
yes, the chroot is run under emulation and that is why the "/usr/bin/qemu-arm-static" should be present
in the target root file system and removed only when everything is set up. It should be created by
qemu-bootstrap command, I wonder why you do not have it. I just tested the procedure with no troubles under Debian/sid.

Can you please retry?
Thanks
