### ISSUE TITLE
Secure-boot, Linux Kernel uImage limited to 8MBytes

### ISSUE THREAD

**Issue by juandiazq** [inversepath/usbarmory#35]
Hello,

I have a problem of signing the uImage when its size is larger than 8MBytes. How could I sign a linux kernel image that could be larger than 8MBytes?

Regards.

**Comment by abarisani** [comment]
Which tool are you using to sign the image and which error are you encountering?

**Comment by juandiazq** [comment]
I am using the CST v2.3.2 from nxp.com.

**Comment by abarisani** [comment]
The secure boot procedure is meant to sign the bootloader, not the kernel. Why are you signing the uImage file? Please follow our wiki for details steps and re-open the issue if necessary. Thanks.
