### ISSUE TITLE
CDC Ethernet and host modes simultaneously?

### ISSUE THREAD

**Issue by anatoli26** [inversepath/usbarmory#39]
Hi,

Is it possible to run Armory in CDC Ethernet and host modes _simultaneously_?

My use-case ("firewall/router") would be to make Armory appear to an attached notebook as a USB modem (CDC Ethernet) via which the notebook would connect to internet, and Armory at the same time having some USB WiFi or USB 3G/4G modems connected to have access to internet, so all traffic goes via Armory, no way for the notebook to connect to internet directly.

Is it possible with the current configuration? If I understand it correctly, Armory can work in either mode separately. Could the GPIOs be somehow used to connect the host USB adapter? If not, do you have plans on manufacturing an Armory version that could be used in both modes simultaneously (i.e. connect it to a notebook and attach to it a USB modem)?

**Comment by andrejro** [comment]
No, it is not possible.
There is only one USB interface on the USB armory, which can act either as USB host or USB device. There are no USB interfaces exposed on the GPIO header.
There are no plans for now for a new USB armory version.
