### ISSUE TITLE
Plans to support SNVS+DCP on i.MX6ULL for MKII

### ISSUE THREAD

**Issue by Isso** [inversepath/usbarmory#46]
You mentioned in [MK II roadmap](https://github.com/inversepath/usbarmory/wiki/Mk-II-Roadmap) that you have plans for a variant with i.MX6ULL for higher speed.

Are there any plans to support SNVS+DCP as you did in [SNVS+CAAM](https://github.com/inversepath/caam-keyblob) on i.MX6UL?

**Comment by abarisani** [comment]
Yes, we plan to support it in exactly the same way. This is a question and not an issue, therefore I will close it, please leave such questions for our support email or discussion group, thanks :).
