### ISSUE TITLE
Wiki: Mk I / Host adapter: Fix link to example device tree source file (dts)

### ISSUE THREAD

**Issue by eduncan911** [inversepath/usbarmory#51]
On this wiki page:

https://github.com/inversepath/usbarmory/wiki/Host-adapter

There's a broken link for the example device tree source file (dts):

> The official USB armory repository provides an example here.

The correct link should be:

https://github.com/inversepath/usbarmory/blob/master/software/kernel_conf/mark-one/imx53-usbarmory-host.dts

**Comment by andrejro** [comment]
Fixed. Thanks!
