### ISSUE TITLE
Getting Started page

### ISSUE THREAD

**Issue by rkt88edmo** [inversepath/usbarmory#6]
"MPORTANT: please note that the microSD slot is with "hinge" type insertion and not a pull-push slot. In order to open it gently ****lift**** the closed metal hinge towards the opposite direction of the little arrow engraved on it, a small "click" indicates successful opening."

Using "lift" is confusing, you need to "slide" the metal tab to unlock it prior to lifting.  Just a wording suggestion.

**Comment by abarisani** [comment]
Fixed. Thanks.
