### ISSUE TITLE
Connecting

### ISSUE THREAD

**Issue by darakian** [inversepath/usbarmory#8]
Hi guys. I downloaded the default image and dd'd it to my sdcard as the instructions state here
http://dev.inversepath.com/download/usbarmory/
When I connect my armory to my laptop (fedora 21) I get a new network device (enp0s26u1u2), but I sshing to 10.0.0.1 fails. I have no route to that address and I'm wondering if I need to set up the route manually. Any thoughts?

Edit:
Tried to add a route via 
route add -net 10.0.0.0 netmask 255.255.255.0 gw 10.0.0.2 dev enp0s26u1u2
and I get back
SIOCADDRT: Network is unreachable

**Comment by andrejro** [comment]
Hi,
did you assign the address to the network interface?

ifconfig enp0s26u1u2 10.0.0.2 netmask 255.255.255.0

**Comment by darakian** [comment]
I had not. That got a response, but now ssh doesn't seem to connect. I get the key exchange, I accept the key, and then nothing. Web interface is also non-responsive.The SSH key comes up as ECDSA, is this maybe not supported by the fedora config of openssh?

**Comment by abarisani** [comment]
On Sun, Mar 29, 2015 at 05:28:33PM -0700, Jon Moroney wrote:
> I had not. That got a response, but now ssh doesn't seem to connect. I get the key exchange, I accept the key, and then nothing. Web interface is also non-responsive.The SSH key comes up as ECDSA, is this maybe not supported by the fedora config of openssh?
>

Could you please cut & paste the output of the ssh exchange (including the
ssh command used) as well as the one from the following commands (executed
as root or with sudo): 

ip addr
ip route

**Comment by darakian** [comment]
@abarisani The issue was resolved. It turns out that network manager was overwriting the ip info that I had given to the interface. Adding the IP info via network manager solved this.

**Comment by abarisani** [comment]
Excellent, thanks for the update.
