### ISSUE TITLE
Some commentary on preparing bootable sd cards

### ISSUE THREAD

**Issue by ckuethe** [inversepath/usbarmory#9]
It is not necessary to install ia32 libraries on recent versions of ubuntu (and probably debian too) if the cross-compilers are new enough.

Ubuntu 15.04 development releases work as a cross-development platform.

In the instructions for preparing debian images you should add "fake-hwclock" to the list of packages to install. This will store a timestamp in the filesystem at reasonable intervals and restore it at boot, so that time isn't reset to the epoch at power loss... https://packages.debian.org/wheezy/admin/fake-hwclock

Additionally, it may be worth mentioning "mg" for people who like emacs... https://packages.debian.org/wheezy/editors/mg

Also, it would be more portable to use "printf" rather than "echo -e" in the instructions.

**Comment by abarisani** [comment]
Installing ia32 doesn't hurt and ensures little more compatibility, I'd rather keep that.

I changed the FAQ to include fake-hwclock and I also added it to the preparation instructions.

Regarding "mg" I don't want to enter the rabbit hole of adding a lot of default packages, I think people that require some would be expert enough to add them during the installation procedure or afterwards ;).

As "printf" behaves different than "echo -e", and considering that the instructions are meant for Debian or Ubuntu anyway, meaning there would be other portability issues, I'd rather keep it as it is.

Thanks!
